In [1]:
import pandas as pd

ALC_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/ALC_All.csv")
Geo_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/Geo_All.csv")
Pro_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/Prof_All.csv")

/var/folders/_v/58p7csjn63j_snd2sxrghlr00000gn/T/ipykernel_26649/3552317567.py:3: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  ALC_df = pd.read_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/ALC_All.csv")

In [2]:
print("ALC", ALC_df.shape)
print("Geo", Geo_df.shape)
print("Pro", Pro_df.shape)

ALC (594187, 12)
Geo (5859, 5)
Pro (1373, 8)

In [3]:
ALC_df.head()

,File,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,Label,Concat,Occurances
0,ALC_24,100001,45-3031,1,18.88,18.88,18.88,18.88,18.88,NaN,100001 -45-3031-1,1
1,ALC_25,100001,11-1011,2,46.05,74.94,103.82,132.71,104.11,NaN,100001-11-1011-2,1
2,ALC_25,100001,11-2011,2,37.63,47.96,58.30,68.63,58.40,NaN,100001-11-2011-2,1
3,ALC_24,100001,11-9041,2,44.25,56.69,69.14,81.58,69.26,NaN,100001-11-9041-2,1
4,ALC_25,100001,11-9072,2,14.58,22.79,31.01,39.22,31.09,NaN,100001-11-9072-2,1

In [4]:
Geo_df.head()

,Area,AreaName,StateAb,State,CountyTownName
0,1000005,Sussex Delaware nonmetropolitan area,DE,Delaware,Sussex County
1,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County
2,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Fayette County
3,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Franklin County
4,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Lamar County

In [5]:
Pro_df.head()

,OES_SOCCODE,OES_SOCCODE_True,OES_SOCTITLE,TruncOnetCode,TruncOnetCode_True,OnetCode,ONetTitle,Concat
0,11-1011,11-1011,Chief Executives,11-1011,11-1011,11-1011.00,Chief Executives,11-1011-Chief Executives-11-1011.00-Chief Exec...
1,11-1011,11-1011,Chief Executives,11-1011,11-1011,11-1011.03,Chief Sustainability Officers,11-1011-Chief Executives-11-1011.03-Chief Sust...
2,11-1021,11-1021,General and Operations Managers,11-1021,11-1021,11-1021.00,General and Operations Managers,11-1021-General and Operations Managers-11-102...
3,11-1031,11-1031,Legislators,11-1031,11-1031,11-1031.00,Legislators,11-1031-Legislators-11-1031.00-Legislators
4,2011-11-01 00:00:00,11-2011,Advertising and Promotions Managers,2011-11-01 00:00:00,11-2011,11-2011.00,Advertising and Promotions Managers,11-2011-Advertising and Promotions Managers-11...

In [6]:
ALC_df[ALC_df['SocCode'] == "11-2011"]

,File,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,Label,Concat,Occurances
2,ALC_25,100001,11-2011,2,37.63,47.96,58.30,68.63,58.40,NaN,100001-11-2011-2,1
1028,ALC_25,10380,11-2011,2,24.75,37.79,50.84,63.88,50.97,NaN,10380-11-2011-2,1
2192,ALC_25,10740,11-2011,1,38.22,53.20,68.18,83.16,68.33,NaN,10740-11-2011-1,1
2657,ALC_24,10900,11-2011,2,52.32,72.46,92.61,112.75,92.81,NaN,10900-11-2011-2,1
2781,ALC_24,11020,11-2011,3,31.27,41.49,51.71,61.93,51.81,NaN,11020-11-2011-3,1
...,...,...,...,...,...,...,...,...,...,...,...,...
540335,ALC26,5400002,11-2011,4,34.78,53.18,71.58,89.98,71.76,NaN,5400002-11-2011-4,1
540768,ALC26,5600006,11-2011,4,34.78,53.18,71.58,89.98,71.76,NaN,5600006-11-2011-4,2
541055,ALC26,5600007,11-2011,4,34.78,53.18,71.58,89.98,71.76,NaN,5600007-11-2011-4,2
541344,ALC26,6600001,11-2011,4,34.78,53.18,71.58,89.98,71.76,NaN,6600001-11-2011-4,2
542146,ALC26,7800001,11-2011,4,34.78,53.18,71.58,89.98,71.76,NaN,7800001-11-2011-4,2

In [9]:
Pro_df[Pro_df['OES_SOCCODE_True'] == "11-2011"]

,OES_SOCCODE,OES_SOCCODE_True,OES_SOCTITLE,TruncOnetCode,TruncOnetCode_True,OnetCode,ONetTitle,Concat
4,2011-11-01 00:00:00,11-2011,Advertising and Promotions Managers,2011-11-01 00:00:00,11-2011,11-2011.00,Advertising and Promotions Managers,11-2011-Advertising and Promotions Managers-11...
5,2011-11-01 00:00:00,11-2011,Advertising and Promotions Managers,2011-11-01 00:00:00,11-2011,11-2011.01,Green Marketers,11-2011-Advertising and Promotions Managers-11...

In [19]:
key_a

'SocCode'

In [20]:
key_b

'OES_SOCCODE_True'

In [13]:
A= ALC_df
B=Geo_df

key_a = A.columns[1]   # 'id'
key_b = B.columns[0]   # 'id'

# B_indexed = B.set_index(key_b)  # set B's key as index for lookup
B_indexed = B.drop_duplicates(subset=key_b, keep='first').set_index(key_b)

for col in B_indexed.columns:
    A[col] = A[key_a].map(B_indexed[col])

In [21]:
B=Pro_df
key_a = A.columns[2]   # 'id'
key_b = B.columns[1]   # 'id'

# # B_indexed = B.set_index(key_b)  # set B's key as index for lookup
B_indexed = B.drop_duplicates(subset=key_b, keep='first').set_index(key_b)

for col in B_indexed.columns:
    A[col] = A[key_a].map(B_indexed[col])

In [19]:
Pro_df[Pro_df['OES_SOCTITLE'] == 'Software Developers']

,OES_SOCCODE,OES_SOCTITLE,TruncOnetCode,OnetCode,ONetTitle
122,15-1252,Software Developers,15-1252,15-1252.00,Software Developers

In [20]:
ALC_df[ALC_df['SocCode'] == '15-1252']

,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,Label
42,10180,15-1252,1,32.10,41.48,50.85,60.23,50.94,NaN
293,10380,15-1252,1,22.72,30.00,37.28,44.56,37.36,NaN
492,10420,15-1252,1,32.92,42.32,51.72,61.12,51.82,NaN
905,10500,15-1252,1,36.90,44.90,52.89,60.89,52.97,NaN
1124,10540,15-1252,1,41.44,51.31,61.18,71.05,61.27,NaN
...,...,...,...,...,...,...,...,...,...
284396,3100001,15-1252,2,34.19,42.78,51.37,59.96,51.45,NaN
298094,4800005,15-1252,2,40.67,50.98,61.28,71.59,61.39,NaN
302040,5400001,15-1252,2,34.28,42.92,51.56,60.20,51.65,NaN
304108,7200006,15-1252,2,18.64,25.72,32.81,39.89,32.88,NaN
396642,6600001,15-1252,4,42.54,55.95,69.37,82.78,69.50,NaN

In [22]:
A

,File,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,Label,...,AreaName,StateAb,State,CountyTownName,OES_SOCCODE,OES_SOCTITLE,TruncOnetCode,TruncOnetCode_True,OnetCode,ONetTitle
0,ALC_24,100001,45-3031,1,18.88,18.88,18.88,18.88,18.88,NaN,...,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County,45-3031,Fishing and Hunting Workers,45-3031,45-3031,45-3031.00,Fishing and Hunting Workers
1,ALC_25,100001,11-1011,2,46.05,74.94,103.82,132.71,104.11,NaN,...,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County,11-1011,Chief Executives,11-1011,11-1011,11-1011.00,Chief Executives
2,ALC_25,100001,11-2011,2,37.63,47.96,58.30,68.63,58.40,NaN,...,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County,2011-11-01 00:00:00,Advertising and Promotions Managers,2011-11-01 00:00:00,11-2011,11-2011.00,Advertising and Promotions Managers
3,ALC_24,100001,11-9041,2,44.25,56.69,69.14,81.58,69.26,NaN,...,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County,9041-11-01 00:00:00,Architectural and Engineering Managers,9041-11-01 00:00:00,11-9041,11-9041.00,Architectural and Engineering Managers
4,ALC_25,100001,11-9072,2,14.58,22.79,31.01,39.22,31.09,NaN,...,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County,9072-11-01 00:00:00,"Entertainment and Recreation Managers, Except ...",9072-11-01 00:00:00,11-9072,11-9072.00,"Entertainment and Recreation Managers, Except ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594182,ALC26,43100,45-3031,3,20.84,20.84,20.84,20.84,20.84,NaN,...,"Sheboygan, WI",WI,Wisconsin,Sheboygan County,45-3031,Fishing and Hunting Workers,45-3031,45-3031,45-3031.00,Fishing and Hunting Workers
594183,ALC26,48260,45-3031,3,20.36,20.36,20.36,20.36,20.36,NaN,...,"Weirton-Steubenville, WV-OH",OH,Ohio,Jefferson County,45-3031,Fishing and Hunting Workers,45-3031,45-3031,45-3031.00,Fishing and Hunting Workers
594184,ALC26,3900002,45-3031,1,21.43,21.43,21.43,21.43,21.43,NaN,...,North Northeastern Ohio non-metropolitan area ...,OH,Ohio,Ashland County,45-3031,Fishing and Hunting Workers,45-3031,45-3031,45-3031.00,Fishing and Hunting Workers
594185,ALC26,6600001,45-3031,1,20.39,20.39,20.39,20.39,20.39,NaN,...,Guam MSA,GU,GUAM,ADELUP,45-3031,Fishing and Hunting Workers,45-3031,45-3031,45-3031.00,Fishing and Hunting Workers
594186,ALC26,7800001,45-3031,1,19.27,19.27,19.27,19.27,19.27,NaN,...,U.S. Virgin Islands MSA,VI,VIRGIN ISLANDS,ST. CROIX,45-3031,Fishing and Hunting Workers,45-3031,45-3031,45-3031.00,Fishing and Hunting Workers

In [30]:
A.to_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/merged3yrsV2.csv", index=False)

In [31]:
sampled_df = A.sample(n=50000)
sampled_df = sampled_df.reset_index(drop=True)

In [32]:
sampled_df.to_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/sampleMerged.csv", index=False)

In [8]:
import csv, json

rows = []
titles = set()
with open('/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/merged.csv') as f:
    reader = csv.DictReader(f)
    for row in reader:
        titles.add(row['OES_SOCTITLE'])
        rows.append([
            row['CountyTownName'],
            row['StateAb'],
            row['OES_SOCTITLE'],
            row['Level1'],
            row['Level2'],
            row['Level3'],
            row['Level4'],
            row['Average']
        ])

out = {'titles': sorted(titles), 'rows': rows}
print(json.dumps(out, separators=(',', ':')))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [2]:
out

{'titles': ['Accountants and Auditors',
  'Actors',
  'Actuaries',
  'Acupuncturists',
  'Adhesive Bonding Machine Operators and Tenders',
  'Administrative Law Judges, Adjudicators, and Hearing Officers',
  'Administrative Services Managers',
  'Adult Basic Education, Adult Secondary Education, and English as a Second Language Instructors',
  'Advertising Sales Agents',
  'Advertising and Promotions Managers',
  'Aerospace Engineering and Operations Technologists and Technicians',
  'Aerospace Engineers',
  'Agents and Business Managers of Artists, Performers, and Athletes',
  'Agricultural Engineers',
  'Agricultural Equipment Operators',
  'Agricultural Inspectors',
  'Agricultural Sciences Teachers, Postsecondary',
  'Agricultural Technicians',
  'Agricultural Workers, All Other',
  'Air Traffic Controllers',
  'Aircraft Cargo Handling Supervisors',
  'Aircraft Mechanics and Service Technicians',
  'Aircraft Service Attendants',
  'Aircraft Structure, Surfaces, Rigging, and Systems Assemblers',
  'Airfield Operations Specialists',
  'Airline Pilots, Copilots, and Flight Engineers',
  'Ambulance Drivers and Attendants, Except Emergency Medical Technicians',
  'Amusement and Recreation Attendants',
  'Anesthesiologists',
  'Animal Breeders',
  'Animal Caretakers',
  'Animal Control Workers',
  'Animal Scientists',
  'Animal Trainers',
  'Anthropologists and Archeologists',
  'Anthropology and Archeology Teachers, Postsecondary',
  'Appraisers and Assessors of Real Estate',
  'Appraisers of Personal and Business Property',
  'Arbitrators, Mediators, and Conciliators',
  'Architects, Except Landscape and Naval',
  'Architectural and Civil Drafters',
  'Architectural and Engineering Managers',
  'Architecture Teachers, Postsecondary',
  'Archivists',
  'Area, Ethnic, and Cultural Studies Teachers, Postsecondary',
  'Art Directors',
  'Art, Drama, and Music Teachers, Postsecondary',
  'Artists and Related Workers, All Other',
  'Assemblers and Fabricators, All Other',
  'Astronomers',
  'Athletes and Sports Competitors',
  'Athletic Trainers',
  'Atmospheric and Space Scientists',
  'Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary',
  'Audio and Video Technicians',
  'Audiologists',
  'Audiovisual Equipment Installers and Repairers',
  'Automotive Body and Related Repairers',
  'Automotive Glass Installers and Repairers',
  'Automotive Service Technicians and Mechanics',
  'Automotive and Watercraft Service Attendants',
  'Avionics Technicians',
  'Baggage Porters and Bellhops',
  'Bailiffs',
  'Bakers',
  'Barbers',
  'Bartenders',
  'Bicycle Repairers',
  'Bill and Account Collectors',
  'Billing and Posting Clerks',
  'Biochemists and Biophysicists',
  'Bioengineers and Biomedical Engineers',
  'Biological Science Teachers, Postsecondary',
  'Biological Scientists, All Other',
  'Biological Technicians',
  'Boilermakers',
  'Bookkeeping, Accounting, and Auditing Clerks',
  'Brickmasons and Blockmasons',
  'Bridge and Lock Tenders',
  'Broadcast Announcers and Radio Disc Jockeys',
  'Broadcast Technicians',
  'Brokerage Clerks',
  'Budget Analysts',
  'Building Cleaning Workers, All Other',
  'Bus Drivers, School',
  'Bus Drivers, Transit and Intercity',
  'Bus and Truck Mechanics and Diesel Engine Specialists',
  'Business Operations Specialists, All Other',
  'Business Teachers, Postsecondary',
  'Butchers and Meat Cutters',
  'Buyers and Purchasing Agents, Farm Products',
  'Cabinetmakers and Bench Carpenters',
  'Calibration Technologists and Technicians',
  'Camera Operators, Television, Video, and Film',
  'Camera and Photographic Equipment Repairers',
  'Captains, Mates, and Pilots of Water Vessels',
  'Cardiologists',
  'Cardiovascular Technologists and Technicians',
  'Career/Technical Education Teachers, Middle School',
  'Career/Technical Education Teachers, Postsecondary',
  'Career/Technical Education Teachers, Secondary School',
  'Cargo and Freight Agents',
  'Carpenters',
  'Carpet Installers',
  'Cartographers and Photogrammetrists',
  'Cashiers',
  'Cement Masons and Concrete Finishers',
  'Chefs and Head Cooks',
  'Chemical Engineers',
  'Chemical Equipment Operators and Tenders',
  'Chemical Plant and System Operators',
  'Chemical Technicians',
  'Chemistry Teachers, Postsecondary',
  'Chemists',
  'Chief Executives',
  'Child, Family, and School Social Workers',
  'Childcare Workers',
  'Chiropractors',
  'Choreographers',
  'Civil Engineering Technologists and Technicians',
  'Civil Engineers',
  'Claims Adjusters, Examiners, and Investigators',
  'Cleaners of Vehicles and Equipment',
  'Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders',
  'Clergy',
  'Clinical and Counseling Psychologists',
  'Coaches and Scouts',
  'Coating, Painting, and Spraying Machine Setters, Operators, and Tenders',
  'Coil Winders, Tapers, and Finishers',
  'Coin, Vending, and Amusement Machine Servicers and Repairers',
  'Commercial Divers',
  'Commercial Pilots',
  'Commercial and Industrial Designers',
  'Communications Equipment Operators, All Other',
  'Communications Teachers, Postsecondary',
  'Community Health Workers',
  'Community and Social Service Specialists, All Other',
  'Compensation and Benefits Managers',
  'Compensation, Benefits, and Job Analysis Specialists',
  'Compliance Officers',
  'Computer Hardware Engineers',
  'Computer Network Architects',
  'Computer Network Support Specialists',
  'Computer Numerically Controlled Tool Operators',
  'Computer Numerically Controlled Tool Programmers',
  'Computer Occupations, All Other',
  'Computer Programmers',
  'Computer Science Teachers, Postsecondary',
  'Computer Systems Analysts',
  'Computer User Support Specialists',
  'Computer and Information Research Scientists',
  'Computer and Information Systems Managers',
  'Computer, Automated Teller, and Office Machine Repairers',
  'Concierges',
  'Conservation Scientists',
  'Construction Laborers',
  'Construction Managers',
  'Construction and Building Inspectors',
  'Continuous Mining Machine Operators',
  'Control and Valve Installers and Repairers, Except Mechanical Door',
  'Conveyor Operators and Tenders',
  'Cooks, All Other',
  'Cooks, Fast Food',
  'Cooks, Institution and Cafeteria',
  'Cooks, Private Household',
  'Cooks, Restaurant',
  'Cooks, Short Order',
  'Cooling and Freezing Equipment Operators and Tenders',
  'Correctional Officers and Jailers',
  'Correspondence Clerks',
  'Cost Estimators',
  'Costume Attendants',
  'Counselors, All Other',
  'Counter and Rental Clerks',
  'Couriers and Messengers',
  'Court Reporters and Simultaneous Captioners',
  'Court, Municipal, and License Clerks',
  'Craft Artists',
  'Crane and Tower Operators',
  'Credit Analysts',
  'Credit Authorizers, Checkers, and Clerks',
  'Credit Counselors',
  'Crematory Operators',
  'Criminal Justice and Law Enforcement Teachers, Postsecondary',
  'Crossing Guards and Flaggers',
  'Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders',
  'Curators',
  'Customer Service Representatives',
  'Cutters and Trimmers, Hand',
  'Cutting and Slicing Machine Setters, Operators, and Tenders',
  'Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic',
  'Cytotechnologists',
  'Dancers',
  'Data Entry Keyers',
  'Data Scientists',
  'Database Administrators',
  'Database Architects',
  'Demonstrators and Product Promoters',
  'Dental Assistants',
  'Dental Hygienists',
  'Dental Laboratory Technicians',
  'Dentists, All Other Specialists',
  'Dentists, General',
  'Dermatologists',
  'Derrick Operators, Oil and Gas',
  'Designers, All Other',
  'Desktop Publishers',
  'Detectives and Criminal Investigators',
  'Diagnostic Medical Sonographers',
  'Dietetic Technicians',
  'Dietitians and Nutritionists',
  'Dining Room and Cafeteria Attendants and Bartender Helpers',
  'Directors, Religious Activities and Education',
  'Disc Jockeys, Except Radio',
  'Dishwashers',
  'Dispatchers, Except Police, Fire, and Ambulance',
  'Door-to-Door Sales Workers, News and Street Vendors, and Related Workers',
  'Drafters, All Other',
  'Dredge Operators',
  'Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
  'Driver/Sales Workers',
  'Drywall and Ceiling Tile Installers',
  'Earth Drillers, Except Oil and Gas',
  'Economics Teachers, Postsecondary',
  'Economists',
  'Editors',
  'Education Administrators, All Other',
  'Education Administrators, Kindergarten through Secondary',
  'Education Administrators, Postsecondary',
  'Education Teachers, Postsecondary',
  'Education and Childcare Administrators, Preschool and Daycare',
  'Educational Instruction and Library Workers, All Other',
  'Educational, Guidance, and Career Counselors and Advisors',
  'Electric Motor, Power Tool, and Related Repairers',
  'Electrical Engineers',
  'Electrical Power-Line Installers and Repairers',
  'Electrical and Electronic Engineering Technologists and Technicians',
  'Electrical and Electronic Equipment Assemblers',
  'Electrical and Electronics Drafters',
  'Electrical and Electronics Installers and Repairers, Transportation Equipment',
  'Electrical and Electronics Repairers, Commercial and Industrial Equipment',
  'Electrical and Electronics Repairers, Powerhouse, Substation, and Relay',
  'Electricians',
  'Electro-Mechanical and Mechatronics Technologists and Technicians',
  'Electromechanical Equipment Assemblers',
  'Electronic Equipment Installers and Repairers, Motor Vehicles',
  'Electronics Engineers, Except Computer',
  'Elementary School Teachers, Except Special Education',
  'Elevator and Escalator Installers and Repairers',
  'Eligibility Interviewers, Government Programs',
  'Embalmers',
  'Emergency Management Directors',
  'Emergency Medical Technicians',
  'Emergency Medicine Physicians',
  'Engine and Other Machine Assemblers',
  'Engineering Teachers, Postsecondary',
  'Engineering Technologists and Technicians, Except Drafters, All Other',
  'Engineers, All Other',
  'English Language and Literature Teachers, Postsecondary',
  'Entertainers and Performers, Sports and Related Workers, All Other',
  'Entertainment Attendants and Related Workers, All Other',
  'Entertainment and Recreation Managers, Except Gambling',
  'Environmental Engineering Technologists and Technicians',
  'Environmental Engineers',
  'Environmental Science Teachers, Postsecondary',
  'Environmental Science and Protection Technicians, Including Health',
  'Environmental Scientists and Specialists, Including Health',
  'Epidemiologists',
  'Etchers and Engravers',
  'Excavating and Loading Machine and Dragline Operators, Surface Mining',
  'Executive Secretaries and Executive Administrative Assistants',
  'Exercise Physiologists',
  'Exercise Trainers and Group Fitness Instructors',
  'Explosives Workers, Ordnance Handling Experts, and Blasters',
  'Extraction Workers, All Other',
  'Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic',
  'Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers',
  'Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders',
  'Fabric and Apparel Patternmakers',
  'Facilities Managers',
  'Fallers',
  'Family Medicine Physicians',
  'Family and Consumer Sciences Teachers, Postsecondary',
  'Farm Equipment Mechanics and Service Technicians',
  'Farm Labor Contractors',
  'Farm and Home Management Educators',
  'Farmers, Ranchers, and Other Agricultural Managers',
  'Farmworkers and Laborers, Crop, Nursery, and Greenhouse',
  'Farmworkers, Farm, Ranch, and Aquacultural Animals',
  'Fashion Designers',
  'Fast Food and Counter Workers',
  'Fence Erectors',
  'Fiberglass Laminators and Fabricators',
  'File Clerks',
  'Film and Video Editors',
  'Financial Clerks, All Other',
  'Financial Examiners',
  'Financial Managers',
  'Financial Risk Specialists',
  'Financial Specialists, All Other',
  'Financial and Investment Analysts',
  'Fine Artists, Including Painters, Sculptors, and Illustrators',
  'Fire Inspectors and Investigators',
  'Firefighters',
  'First-Line Supervisors of Construction Trades and Extraction Workers',
  'First-Line Supervisors of Correctional Officers',
  'First-Line Supervisors of Entertainment and Recreation Workers, Except Gambling Services',
  'First-Line Supervisors of Farming, Fishing, and Forestry Workers',
  'First-Line Supervisors of Firefighting and Prevention Workers',
  'First-Line Supervisors of Food Preparation and Serving Workers',
  'First-Line Supervisors of Gambling Services Workers',
  'First-Line Supervisors of Helpers, Laborers, and Material Movers, Hand',
  'First-Line Supervisors of Housekeeping and Janitorial Workers',
  'First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers',
  'First-Line Supervisors of Material-Moving Machine and Vehicle Operators',
  'First-Line Supervisors of Mechanics, Installers, and Repairers',
  'First-Line Supervisors of Non-Retail Sales Workers',
  'First-Line Supervisors of Office and Administrative Support Workers',
  'First-Line Supervisors of Passenger Attendants',
  'First-Line Supervisors of Personal Service Workers',
  'First-Line Supervisors of Police and Detectives',
  'First-Line Supervisors of Production and Operating Workers',
  'First-Line Supervisors of Protective Service Workers, All Other',
  'First-Line Supervisors of Retail Sales Workers',
  'First-Line Supervisors of Security Workers',
  'First-Line Supervisors of Transportation Workers, All Other',
  'Fish and Game Wardens',
  'Fishing and Hunting Workers',
  'Flight Attendants',
  'Floor Layers, Except Carpet, Wood, and Hard Tiles',
  'Floor Sanders and Finishers',
  'Floral Designers',
  'Food Batchmakers',
  'Food Cooking Machine Operators and Tenders',
  'Food Preparation Workers',
  'Food Preparation and Serving Related Workers, All Other',
  'Food Processing Workers, All Other',
  'Food Science Technicians',
  'Food Scientists and Technologists',
  'Food Servers, Nonrestaurant',
  'Food Service Managers',
  'Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders',
  'Foreign Language and Literature Teachers, Postsecondary',
  'Forensic Science Technicians',
  'Forest Fire Inspectors and Prevention Specialists',
  'Forest and Conservation Technicians',
  'Forest and Conservation Workers',
  'Foresters',
  'Forestry and Conservation Science Teachers, Postsecondary',
  'Forging Machine Setters, Operators, and Tenders, Metal and Plastic',
  'Foundry Mold and Coremakers',
  'Fundraisers',
  'Fundraising Managers',
  'Funeral Attendants',
  'Funeral Home Managers',
  'Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders',
  'Furniture Finishers',
  'Gambling Cage Workers',
  'Gambling Change Persons and Booth Cashiers',
  'Gambling Dealers',
  'Gambling Managers',
  'Gambling Service Workers, All Other',
  'Gambling Surveillance Officers and Gambling Investigators',
  'Gambling and Sports Book Writers and Runners',
  'Gas Compressor and Gas Pumping Station Operators',
  'Gas Plant Operators',
  'General Internal Medicine Physicians',
  'General and Operations Managers',
  'Genetic Counselors',
  'Geographers',
  'Geography Teachers, Postsecondary',
  'Geological Technicians, Except Hydrologic Technicians',
  'Geoscientists, Except Hydrologists and Geographers',
  'Glaziers',
  'Graders and Sorters, Agricultural Products',
  'Graphic Designers',
  'Grinding and Polishing Workers, Hand',
  'Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
  'Grounds Maintenance Workers, All Other',
  'Hairdressers, Hairstylists, and Cosmetologists',
  'Hazardous Materials Removal Workers',
  'Health Education Specialists',
  'Health Information Technologists and Medical Registrars',
  'Health Specialties Teachers, Postsecondary',
  'Health Technologists and Technicians, All Other',
  'Health and Safety Engineers, Except Mining Safety Engineers and Inspectors',
  'Healthcare Diagnosing or Treating Practitioners, All Other',
  'Healthcare Practitioners and Technical Workers, All Other',
  'Healthcare Social Workers',
  'Healthcare Support Workers, All Other',
  'Hearing Aid Specialists',
  'Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic',
  'Heating, Air Conditioning, and Refrigeration Mechanics and Installers',
  'Heavy and Tractor-Trailer Truck Drivers',
  'Helpers, Construction Trades, All Other',
  'Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters',
  'Helpers--Carpenters',
  'Helpers--Electricians',
  'Helpers--Extraction Workers',
  'Helpers--Installation, Maintenance, and Repair Workers',
  'Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons',
  'Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters',
  'Helpers--Production Workers',
  'Helpers--Roofers',
  'Highway Maintenance Workers',
  'Histology Technicians',
  'Historians',
  'History Teachers, Postsecondary',
  'Hoist and Winch Operators',
  'Home Appliance Repairers',
  'Home Health Aides',
  'Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop',
  'Hotel, Motel, and Resort Desk Clerks',
  'Human Resources Assistants, Except Payroll and Timekeeping',
  'Human Resources Managers',
  'Human Resources Specialists',
  'Hydrologic Technicians',
  'Hydrologists',
  'Industrial Engineering Technologists and Technicians',
  'Industrial Engineers',
  'Industrial Machinery Mechanics',
  'Industrial Production Managers',
  'Industrial Truck and Tractor Operators',
  'Industrial-Organizational Psychologists',
  'Information Security Analysts',
  'Information and Record Clerks, All Other',
  'Inspectors, Testers, Sorters, Samplers, and Weighers',
  'Installation, Maintenance, and Repair Workers, All Other',
  'Instructional Coordinators',
  'Insulation Workers, Floor, Ceiling, and Wall',
  'Insulation Workers, Mechanical',
  'Insurance Appraisers, Auto Damage',
  'Insurance Claims and Policy Processing Clerks',
  'Insurance Sales Agents',
  'Insurance Underwriters',
  'Interior Designers',
  'Interpreters and Translators',
  'Interviewers, Except Eligibility and Loan',
  'Janitors and Cleaners, Except Maids and Housekeeping Cleaners',
  'Jewelers and Precious Stone and Metal Workers',
  'Judges, Magistrate Judges, and Magistrates',
  'Judicial Law Clerks',
  'Kindergarten Teachers, Except Special Education',
  'Labor Relations Specialists',
  'Laborers and Freight, Stock, and Material Movers, Hand',
  'Landscape Architects',
  'Landscaping and Groundskeeping Workers',
  'Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic',
  'Laundry and Dry-Cleaning Workers',
  'Law Teachers, Postsecondary',
  'Lawyers',
  'Layout Workers, Metal and Plastic',
  'Legal Secretaries and Administrative Assistants',
  'Legal Support Workers, All Other',
  'Legislators',
  'Librarians and Media Collections Specialists',
  'Library Assistants, Clerical',
  'Library Science Teachers, Postsecondary',
  'Library Technicians',
  'Licensed Practical and Licensed Vocational Nurses',
  'Life Scientists, All Other',
  'Life, Physical, and Social Science Technicians, All Other',
  'Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers',
  'Light Truck Drivers',
  'Lighting Technicians',
  'Loading and Moving Machine Operators, Underground Mining',
  'Loan Interviewers and Clerks',
  'Loan Officers',
  'Locker Room, Coatroom, and Dressing Room Attendants',
  'Locksmiths and Safe Repairers',
  'Locomotive Engineers',
  'Lodging Managers',
  'Log Graders and Scalers',
  'Logging Equipment Operators',
  'Logging Workers, All Other',
  'Logisticians',
  'Machine Feeders and Offbearers',
  'Machinists',
  'Magnetic Resonance Imaging Technologists',
  'Maids and Housekeeping Cleaners',

In [3]:
type(out)

dict

In [9]:
with open("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/mergeEmb.txt", "w") as f:
    f.write(str(out))

In [29]:
A.head(5)

,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,AreaName,StateAb,State,CountyTownName,OES_SOCTITLE,TruncOnetCode_True,OnetCode,ONetTitle
0,100001,45-3031,1,18.88,18.88,18.88,18.88,18.88,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County,Fishing and Hunting Workers,45-3031,45-3031.00,Fishing and Hunting Workers
1,100001,11-1011,2,46.05,74.94,103.82,132.71,104.11,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County,Chief Executives,11-1011,11-1011.00,Chief Executives
2,100001,11-2011,2,37.63,47.96,58.30,68.63,58.40,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County,Advertising and Promotions Managers,11-2011,11-2011.00,Advertising and Promotions Managers
3,100001,11-9041,2,44.25,56.69,69.14,81.58,69.26,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County,Architectural and Engineering Managers,11-9041,11-9041.00,Architectural and Engineering Managers
4,100001,11-9072,2,14.58,22.79,31.01,39.22,31.09,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County,"Entertainment and Recreation Managers, Except ...",11-9072,11-9072.00,"Entertainment and Recreation Managers, Except ..."

In [26]:
# Remove unnecessary columns
A = A.drop(columns=['File', 'Label', 'Occurances', 'OES_SOCCODE', 'TruncOnetCode', 'Concat'])

In [28]:
A = A.drop(columns=['Concat'])