In [7]:
import pandas as pd

ALC_df = pd.read_excel("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/ALC24_25_Py.xlsx")

In [8]:
df = ALC_df
df

,File,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,Label,Concat,Occurances
0,ALC_24,100001,45-3031,1,18.88,18.88,18.88,18.88,18.88,NaN,100001 -45-3031-1,1
1,ALC_25,100001,11-1011,2,46.05,74.94,103.82,132.71,104.11,NaN,100001-11-1011-2,1
2,ALC_25,100001,11-1021,1,24.19,39.31,54.43,69.55,54.58,NaN,100001-11-1021-1,2
3,ALC_25,100001,11-1031,1,19560.00,27760.00,35960.00,44160.00,36040.00,Annual Wage,100001-11-1031-1,2
4,ALC_25,100001,11-2011,2,37.63,47.96,58.30,68.63,58.40,NaN,100001-11-2011-2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
963302,ALC26,43100,45-3031,3,20.84,20.84,20.84,20.84,20.84,NaN,43100-45-3031-3,2
963303,ALC26,48260,45-3031,3,20.36,20.36,20.36,20.36,20.36,NaN,48260-45-3031-3,1
963304,ALC26,3900002,45-3031,1,21.43,21.43,21.43,21.43,21.43,NaN,3900002-45-3031-1,2
963305,ALC26,6600001,45-3031,1,20.39,20.39,20.39,20.39,20.39,NaN,6600001-45-3031-1,2
963306,ALC26,7800001,45-3031,1,19.27,19.27,19.27,19.27,19.27,NaN,7800001-45-3031-1,2

In [13]:
len(df)-len(df[((df["File"] == "ALC_24") & (df["Occurances"] == 2))])

946302

In [10]:
len(df[((df["File"] == "ALC_25") & (df["Occurances"] == 2))])

352115

In [12]:
len(df[((df["File"] == "ALC26") & (df["Occurances"] == 2))])

369120

In [14]:
df = df[~((df["File"] == "ALC_24") & (df["Occurances"] == 2))]
len(df)

946302

In [15]:
len(df)-len(df[((df["File"] == "ALC_25") & (df["Occurances"] == 2))])

594187

In [16]:
df = df[~((df["File"] == "ALC_25") & (df["Occurances"] == 2))]
len(df)

594187

In [17]:
df=df.reset_index(drop=True)

In [18]:
df

,File,Area,SocCode,GeoLvl,Level1,Level2,Level3,Level4,Average,Label,Concat,Occurances
0,ALC_24,100001,45-3031,1,18.88,18.88,18.88,18.88,18.88,NaN,100001 -45-3031-1,1
1,ALC_25,100001,11-1011,2,46.05,74.94,103.82,132.71,104.11,NaN,100001-11-1011-2,1
2,ALC_25,100001,11-2011,2,37.63,47.96,58.30,68.63,58.40,NaN,100001-11-2011-2,1
3,ALC_24,100001,11-9041,2,44.25,56.69,69.14,81.58,69.26,NaN,100001-11-9041-2,1
4,ALC_25,100001,11-9072,2,14.58,22.79,31.01,39.22,31.09,NaN,100001-11-9072-2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
594182,ALC26,43100,45-3031,3,20.84,20.84,20.84,20.84,20.84,NaN,43100-45-3031-3,2
594183,ALC26,48260,45-3031,3,20.36,20.36,20.36,20.36,20.36,NaN,48260-45-3031-3,1
594184,ALC26,3900002,45-3031,1,21.43,21.43,21.43,21.43,21.43,NaN,3900002-45-3031-1,2
594185,ALC26,6600001,45-3031,1,20.39,20.39,20.39,20.39,20.39,NaN,6600001-45-3031-1,2
594186,ALC26,7800001,45-3031,1,19.27,19.27,19.27,19.27,19.27,NaN,7800001-45-3031-1,2

In [20]:
df.to_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/ALC_All.csv", index=False)

In [22]:
xls = pd.ExcelFile("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/Geography23-24-25-26.xlsx")
df1 = pd.read_excel(xls, 'Final_Filter')
df1

,Area,AreaName,StateAb,State,CountyTownName
0,1000005,Sussex Delaware nonmetropolitan area,DE,Delaware,Sussex County
1,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Cullman County
2,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Fayette County
3,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Franklin County
4,100001,Northwest Alabama nonmetropolitan area,AL,Alabama,Lamar County
...,...,...,...,...,...
5854,900001,Connecticut nonmetropolitan area,CT,Connecticut,Sharon town
5855,900001,Connecticut nonmetropolitan area,CT,Connecticut,Torrington town
5856,900001,Connecticut nonmetropolitan area,CT,Connecticut,Warren town
5857,900001,Connecticut nonmetropolitan area,CT,Connecticut,Washington town
5858,900001,Connecticut nonmetropolitan area,CT,Connecticut,Winchester town

In [23]:
df1.to_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/Geo_All.csv", index=False)

In [24]:
xls = pd.ExcelFile("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/Profession23-24-25-26.xlsx")
df2 = pd.read_excel(xls, 'Uniques')
df2

,OES_SOCCODE,OES_SOCCODE_True,OES_SOCTITLE,TruncOnetCode,TruncOnetCode_True,OnetCode,ONetTitle,Concat
0,11-1011,11-1011,Chief Executives,11-1011,11-1011,11-1011.00,Chief Executives,11-1011-Chief Executives-11-1011.00-Chief Exec...
1,11-1011,11-1011,Chief Executives,11-1011,11-1011,11-1011.03,Chief Sustainability Officers,11-1011-Chief Executives-11-1011.03-Chief Sust...
2,11-1021,11-1021,General and Operations Managers,11-1021,11-1021,11-1021.00,General and Operations Managers,11-1021-General and Operations Managers-11-102...
3,11-1031,11-1031,Legislators,11-1031,11-1031,11-1031.00,Legislators,11-1031-Legislators-11-1031.00-Legislators
4,2011-11-01 00:00:00,11-2011,Advertising and Promotions Managers,2011-11-01 00:00:00,11-2011,11-2011.00,Advertising and Promotions Managers,11-2011-Advertising and Promotions Managers-11...
...,...,...,...,...,...,...,...,...
1368,53-7073,53-7073,Wellhead Pumpers,53-7073,53-7073,53-7073.00,Wellhead Pumpers,53-7073-Wellhead Pumpers-53-7073.00-Wellhead P...
1369,53-7081,53-7081,Refuse and Recyclable Material Collectors,53-7081,53-7081,53-7081.00,Refuse and Recyclable Material Collectors,53-7081-Refuse and Recyclable Material Collect...
1370,53-7111,53-7111,Mine Shuttle Car Operators,53-7111,53-7111,53-7111.00,Mine Shuttle Car Operators,53-7111-Mine Shuttle Car Operators-53-7111.00-...
1371,53-7121,53-7121,"Tank Car, Truck, and Ship Loaders",53-7121,53-7121,53-7121.00,"Tank Car, Truck, and Ship Loaders","53-7121-Tank Car, Truck, and Ship Loaders-53-7..."
1372,53-7199,53-7199,"Material Moving Workers, All Other",53-7199,53-7199,53-7199.00,"Material Moving Workers, All Other","53-7199-Material Moving Workers, All Other-53-..."

In [25]:
df2.to_csv("/Users/shubhamarundekatey/Downloads/OFLC_Wages_2025-26_Updated/Prof_All.csv", index=False)